# meta-canary-distro/conf/distro/canary.conf
DISTRO = "canary"
DISTRO_NAME = "canary"
DISTRO_VERSION = "0.1"
DISTRO_CODENAME = "scarthgap"

# Add or remove packages/features as needed
DISTRO_FEATURES:append = " systemd"

# IMAGE_INSTALL:append = " my-custom-app"