# meta-canary-distro/conf/distro/canary.conf
DISTRO = "canary"
DISTRO_NAME = "canary"
DISTRO_VERSION = "0.1"
DISTRO_CODENAME = "scarthgap"

INIT_MANAGER = "mdev-busybox"

# Add or remove packages/features as needed

# IMAGE_INSTALL:append = " my-custom-app"

